planets:
- name: "Sun"
  mass: 1
  position:
    x: 0
    y: 0
  velocity:
    x: 0
    y: 0
  radius: 0.2
  color:
    red: 255
    green: 204
    blue: 64
- name: "Earth"
  mass: 0.000003
  position:
    x: 1
    y: 0
  velocity:
    x: 0
    y: -0.0172
  radius: 0.05
  color:
    red: 100
    green: 149
    blue: 237
- name: "Mars"
  mass: 0.00000037
  position:
    x: 1.52
    y: 0
  velocity:
    x: 0
    y: -0.0129
  radius: 0.04
  color:
    red: 188
    green: 39
    blue: 50
- name: "Jupiter"
  mass: 0.000954
  position:
    x: 5.2
    y: 0
  velocity:
    x: 0
    y: -0.00754
  radius: 0.09
  color:
    red: 210
    green: 180
    blue: 140
- name: "Comet"
  mass: 0.0000000001
  position:
    x: 1.392
    y: 0
  velocity:
    x: 0
    y: -0.019010182
  radius: 0.03
  color:
    red: 200
    green: 200
    blue: 200